
[workspace]
resolver = "2"
members = [
    "actors",
    "bls-utils",
    "bls-unsafe",
    "bindgen-protocol",
]

[profile.actor]
inherits = "release"
panic = "abort"
overflow-checks = true
lto = true
opt-level = "z"
#strip = true
